name: Upload NuGet Package

on:
  workflow_run:
    workflows:
      - 'Update Version'
    types:
      - 'completed'
  workflow_dispatch:
      
defaults:
  run:
    shell: | # Set the default shell for all commands:
           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"

env:
  PROJECT_NAME:             'radj307.ChainConverter'
  BUILD_CONFIGURATION:      'Release'

jobs:
  build-and-publish:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v3.0.2
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run:  |
              dotnet build -c ${{ env.BUILD_CONFIGURATION }}
              
      - name: Push to nuget.org
        run:  |
              Write-Output "","# Pushing to (nuget.org) ..."
              dotnet nuget push bin/${{env.BUILD_CONFIGURATION}}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push to Github Package Registry
        run:  |
              Write-Output "","# Pushing to (Github Package Registry) ..."
              dotnet nuget add source --username radj307 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/radj307/index.json"
              dotnet nuget push bin/${{env.BUILD_CONFIGURATION}}/*.nupkg -k ${{ github.token }} -s https://nuget.pkg.github.com/radj307/index.json --skip-duplicate
              
      - name: Upload Artifact(s)
        uses: actions/upload-artifact@v3.1.1
        with:
          name: nupkg
          path: ${{ github.workspace }}/${{ env.PROJECT_NAME }}/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg
          

  create-release:
    needs:    build-and-publish
    runs-on:  ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path:  ${{github.workspace}}/artifacts

      - run:  ls -lAghR

      - name: 'Create Release'
        uses: softprops/action-gh-release@v1
        with:
          draft:      true
          files:      |
                      ${{github.workspace}}/artifacts/*/*
